# Generated by Django 4.0.10 on 2024-01-17 23:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_agent', models.CharField(max_length=200, verbose_name='Nom de l’agent d’inventaire')),
                ('num_inventory', models.IntegerField(verbose_name='Nombre de comptage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('internal_ref', models.CharField(max_length=200)),
                ('old_ref', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='InventoryLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('quantity_uom', models.CharField(choices=[('unit', 'Unité'), ('coffret', 'Coffret'), ('FL', 'FL'), ('BTE', 'Boite'), ('carton', 'Carton'), ('mc', 'MC')], default='UN', max_length=20)),
                ('expiration_date', models.DateField(verbose_name='Date péremption')),
                ('lot', models.CharField(max_length=200)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.product'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='inventory.zone'),
        ),
    ]
