# Generated by Django 4.0.10 on 2024-01-18 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_sale_uom_product_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylines',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_lines', to='inventory.inventory'),
        ),
    ]
