# Generated by Django 4.0.10 on 2024-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorylines_inventory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylines',
            name='expiration_date',
            field=models.DateField(null=True, verbose_name='Date péremption'),
        ),
    ]
