# Generated by Django 4.0.10 on 2024-01-20 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventorylines_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryProductLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ProductLotLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lot', models.CharField(max_length=200)),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('quantity_uom', models.CharField(choices=[('unit', 'Unité'), ('coffret', 'Coffret'), ('FL', 'FL'), ('BTE', 'Boite'), ('carton', 'Carton'), ('mc', 'MC')], default='unit', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Date péremption')),
                ('inventory_product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_lot_lines', to='inventory.inventoryproductlines')),
            ],
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='product',
        ),
        migrations.AlterField(
            model_name='product',
            name='designation',
            field=models.CharField(max_length=200, verbose_name='Désignation'),
        ),
        migrations.AlterField(
            model_name='product',
            name='internal_ref',
            field=models.CharField(max_length=200, verbose_name='Référence interne'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_ref',
            field=models.CharField(max_length=200, verbose_name='Ancien référence'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sale_uom',
            field=models.CharField(choices=[('unit', 'Unité'), ('coffret', 'Coffret'), ('FL', 'FL'), ('BTE', 'Boite'), ('carton', 'Carton'), ('mc', 'MC')], default='unit', max_length=20, verbose_name='Unité de vente'),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.CharField(max_length=200, verbose_name='Fournisseur'),
        ),
        migrations.DeleteModel(
            name='InventoryLines',
        ),
        migrations.AddField(
            model_name='inventoryproductlines',
            name='inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_product_lines', to='inventory.inventory'),
        ),
        migrations.AddField(
            model_name='inventoryproductlines',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product'),
        ),
    ]
