# Generated by Django 4.0.10 on 2024-02-05 21:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_inventoryproductlines_productlotlines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lot', models.CharField(max_length=200)),
                ('quantity', models.FloatField(verbose_name='Quantité')),
                ('quantity_uom', models.CharField(choices=[('unit', 'Unité'), ('coffret', 'Coffret'), ('FL', 'FL'), ('BTE', 'Boite'), ('carton', 'Carton'), ('mc', 'MC')], default='unit', max_length=20)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Date péremption')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
